dist: trusty

language: rust

services: docker

sudo: required

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master
    - develop

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

env:
  global:
    - CRATE_NAME=gitea-update-checker

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-pc-windows-gnu

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: Tx2kP3YQwr4/BxO+WIsECfoYaYCZ7Y4KNeOxBJgU5e8mAyXTPvj8u+PVRV+vltqZP7CEihEeLj6PTlNVaSdyWCWuS59uEwfwh2PEi0/VAtW5oWd3H1L+nTuL9kd5+BT//aLH+nc6qV/+D8KC2mLrmTRh2e/VVQocvGpA2lMzNedWlyw5BR7RsDDt5tYhUq6zJmAM4GsWfLmbM/8g8kL5K2d8dJO1HNtchum1TMzh0PRzCKY1ivvg8tYhhdIUJkKNjNozt4rqoKggtnDoOF/xH8SE8sWm69GPV2Lk3H2VdJNRs1wJlTtU1f2Jnxw2kaWKrH0ICukKFImPJVqOq81emWyYFu8slh5JZm1SwBZkyUNj/tl3rV5QwBK7YdrFq2w60GdA8wDSnZ+ZCkK+NYRlaHSOHsXlFipwFUttt60AHYBhr3tbWMOW1mhV3vy3fNuvW2pCQq2k7pF8zKS88U/+w5mz4ZMDI1GurH5+GtIBgxorOjHOAna/dr489a/B7Fgsk9R86199MNZiJggxDkgLbwJWIRi/QpTi8IQ8McMwPHOJeGGyI4G2ywpvR0tN09VTu4ZuCHaXQ0ZbEZY1jWFKTimmppXi5ZwQ2cPzWsxoa2QLWwF7sjBDMThyPotDq2omlHmNMh5mrNnhnoKKIlcDz+1cLeTnTo2N6rk3guXf6pw=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
