dist: trusty

language: rust

services: docker

sudo: required

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master
    - develop

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

env:
  global:
    - CRATE_NAME=gitea-update-checker

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "RsLrHXUKTnqzD9KRMxUM4oGJ2P++ntryBGjGO6tA1x69ZbH4vrYJU3sylveAj2Qo8Ugu4PqkxzeXcO1YyKSbGWRpG/mFf8AmGtn6OiV625XL9cQXzHfppl00jLPN7LVrl+k3azoM4d/zUjpMrf4AzHMtjBV/FfjxaoOk0LO/X3mQEQdNOpKzHdyxfGTGJ+c/JSn9xbEZzU60HhC0xzcY0Byk+ZxfElVSBSD4EIgkDaJ5WXPXdqWpTctq8zCsGIKRou53/JAIC3d1BnyiAOiC9iwKIqkMA9jJmkkqYXhfIlmbwWbgLtwZPqhjhd/SbXTMJvDnoGe8U0ZYViiQEmt//54Wd+XwcL5imX9IrQSLXuN45diCJ+QazQKu/TkHxj8NMm11oI7GSIr+D8i+MldGFH2PO1FBKfPm4a158q/HmvClU31HkyD2Bm2HNtLOwbhcSjf18tF8EAMKm+OpJw8VK7A5McVQfy0s5V8pfPMNO2Xf1UNEE3K6txO+99xiHt8Ekc/z1ATkkVAuElttTcNmL79aF46OqdER7LQRq3M3QB10LFCC+ULZm5kIuD8cZhQ7U5Ipb6qG92Oo9LZlp1a9DrRBDsZFrNEmhTTiHa4jzTUc/ZPi/v/3JpRm7Z4pZXLzy08hi9Sv+U4NdwOgCyf2cJZOTnoY2n8+/ovc73wfeag="
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
