[package]
name = "gitea-update-checker"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
clap = "2.31.2"
rayon = "1.0.1"
failure = "0.1.1"
reqwest = "0.8.5"
semver = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
